// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAuth(ctx context.Context, arg CreateAuthParams) (Auth, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAuth(ctx context.Context, email string) (Auth, error)
	GetUser(ctx context.Context, username string) (GetUserRow, error)
	UpdateAuth(ctx context.Context, arg UpdateAuthParams) (Auth, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
