// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, auth_id, username, full_name)
VALUES ($1, $2, $3, $4)
RETURNING id, auth_id, username, full_name, created_at, updated_at
`

type CreateUserParams struct {
	ID       uuid.UUID `json:"id"`
	AuthID   uuid.UUID `json:"auth_id"`
	Username string    `json:"username"`
	FullName string    `json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.AuthID,
		arg.Username,
		arg.FullName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthID,
		&i.Username,
		&i.FullName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, full_name, created_at, updated_at FROM users
WHERE auth_id = $1 LIMIT 1
`

type GetUserRow struct {
	ID        uuid.UUID `json:"id"`
	Username  string    `json:"username"`
	FullName  string    `json:"full_name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetUser(ctx context.Context, authID uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, authID)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET 
   username = COALESCE($1, username), 
   full_name = COALESCE($2, full_name),
   updated_at = $3
WHERE id = $4
RETURNING id, auth_id, username, full_name, created_at, updated_at
`

type UpdateUserParams struct {
	Username  sql.NullString `json:"username"`
	FullName  sql.NullString `json:"full_name"`
	UpdatedAt time.Time      `json:"updated_at"`
	ID        uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Username,
		arg.FullName,
		arg.UpdatedAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthID,
		&i.Username,
		&i.FullName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
