-- +goose Up
ALTER TABLE auth ADD COLUMN restricted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE auth ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;

-- +goose Down
ALTER TABLE auth DROP COLUMN restricted;
ALTER TABLE auth DROP COLUMN deleted;